export const GET_POKE_REQUEST = "GET_POKE_REQUEST";
export const GET_POKE_SUCCESS = "GET_POKE_SUCCESS"
export const GET_POKE_FAILURE = "GET_POKE_FAILURE"

export const ADD_POKE_REQUEST = "ADD_POKE_REQUEST";
export const ADD_POKE_SUCCESS = "ADD_POKE_SUCCESS";
export const ADD_POKE_FAILURE = "ADD_POKE_FAILURE";